### PR TITLE
merge V1.16.1 into production branch

### PR DESCRIPTION
**Pull request by Andrew-Pohl**

### CODE REVIEW

**Comment by Andrew-Pohl** [comment]
@leonprou any chance you can review this then I can make one for V17.1+ with aura fix

**Comment by leonprou** [comment]
Hi @Andrew-Pohl ,
Can you please add a description. I need a summary to understand what was done.
Then there's 4K+ of commits here. Is there any commits you pushed? If yes can you please point to those

**Comment by Andrew-Pohl** [comment]
> Hi @Andrew-Pohl , Can you please add a description. I need a summary to understand what was done. Then there's 4K+ of commits here. Is there any commits you pushed? If yes can you please point to those


It is just a rebase of our changes to add support for fuse onto of V1.16.1 (nothing new added by me :) )

**Review by leonprou — APPROVED** [review]
LGTM

**Pull request merged**
